# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98ca2abaa441cfc55c41ef3390b9b3bbc21c0fa5df94c122564d9108080f3cc9c3656d1eae9d37c8f5b0bee6fced7b9da9248f02758a461534e4817db9e81f01

test:
  secret_key_base: 0dd9478ef019f50683d92c37275e8a086bf461d1106d169e4733fe00b4f46f352c8f36e6608286c6ff60b409382addc911145be1305a15920b0cb77cb7a1628f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
